version: '3.7'

volumes:
  web_data:
    external: true
    name: web_data

services:
  hub:
    image: selenium/hub
    container_name: automation_hub
    ports:
      - "4444:4444"

    environment:
      GRID_MAX_SESSION: 16
      GRID_BROWSER_TIMEOUT: 3000
      GRID_TIMEOUT: 3000

  chrome_worker_1:
    image: selenium/node-chrome
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 2
      NODE_MAX_INSTANCES: 2
    volumes:
      - /dev/shm:/dev/shm
      - c:\Downloads\chrome:/tmp/downloads/chrome
      - web_data:/tmp/downloads

    links:
      - hub
  chrome_worker_2:
    image: selenium/node-chrome
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 2
      NODE_MAX_INSTANCES: 2
    volumes:
      - /dev/shm:/dev/shm
      - c:\Downloads\chrome:/tmp/downloads/chrome
      - web_data:/tmp/downloads
    links:
      - hub
      
  firefox_worker_1:
    image: selenium/node-firefox
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 2
      NODE_MAX_INSTANCES: 2
    volumes:
      - /dev/shm:/dev/shm
      - c:\Downloads\firefox:/tmp/downloads/firefox
      - web_data:/tmp/downloads
    links:
      - hub
      
  firefox_worker_2:
    image: selenium/node-firefox
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 2
      NODE_MAX_INSTANCES: 2
    volumes:
      - /dev/shm:/dev/shm
      - c:\Downloads\firefox:/tmp/downloads/firefox
      - web_data:/tmp/downloads
    links:
      - hub